---
- hosts: localhost
  remote_user: root
  become: yes
  tasks: 
  - name: "Updates"
    include_tasks: "{{ item }}"
    when: imgVersion is version(item | regex_replace('/.*/') | regex_replace('.yaml'), '<')
    with_items: "{{ lookup('fileglob', 'updates/*.yaml').split(',') | sort }}"
